/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.posystem.gui;

/**
 *
 * @author Ren
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        OrderLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        Description = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        Background1 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(89, 171, 227));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 49, 63), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icon.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Icon.setForeground(new java.awt.Color(52, 73, 94));
        Icon.setText("Background Icon");
        Icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IconMouseExited(evt);
            }
        });
        jPanel1.add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 36));

        jPanel2.setBackground(new java.awt.Color(34, 49, 63));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 470, 10));

        OrderLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        OrderLabel1.setForeground(new java.awt.Color(52, 73, 94));
        OrderLabel1.setText("Main Settings");
        OrderLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OrderLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OrderLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OrderLabel1MouseExited(evt);
            }
        });
        jPanel1.add(OrderLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, 36));

        jRadioButton1.setBackground(new java.awt.Color(89, 171, 227));
        jRadioButton1.setText("BLACK");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, -1));

        Description.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        Description.setForeground(new java.awt.Color(52, 73, 94));
        jPanel1.add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 450, 30));

        jRadioButton2.setBackground(new java.awt.Color(89, 171, 227));
        jRadioButton2.setText("CORN FIELD ICON");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 170, -1));

        jRadioButton3.setBackground(new java.awt.Color(89, 171, 227));
        jRadioButton3.setText("BLUE");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, -1));

        jRadioButton4.setBackground(new java.awt.Color(89, 171, 227));
        jRadioButton4.setText("YELLOW");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, -1));

        Background1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Background1.setForeground(new java.awt.Color(52, 73, 94));
        Background1.setText("Background Color");
        Background1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Background1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Background1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Background1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Background1MouseExited(evt);
            }
        });
        jPanel1.add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 36));

        jRadioButton5.setBackground(new java.awt.Color(89, 171, 227));
        jRadioButton5.setText("RED");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, -1));

        jRadioButton6.setBackground(new java.awt.Color(89, 171, 227));
        jRadioButton6.setText("RICE FIELD ICON");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, -1));

        jRadioButton7.setBackground(new java.awt.Color(89, 171, 227));
        jRadioButton7.setText("PANORAMIC BOX ICON");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 170, -1));

        jButton1.setBackground(new java.awt.Color(242, 38, 19));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("CHANGE SETTINGS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconMouseEntered
        Description.setText("Change the icon of central background.");
    }//GEN-LAST:event_IconMouseEntered

    private void IconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconMouseExited
        Description.setText("");
    }//GEN-LAST:event_IconMouseExited

    private void OrderLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderLabel1MouseClicked

    private void OrderLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderLabel1MouseEntered

    private void OrderLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderLabel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderLabel1MouseExited

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void Background1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Background1MouseEntered
        Description.setText("Change the color of menu background.");
    }//GEN-LAST:event_Background1MouseEntered

    private void Background1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Background1MouseExited
        Description.setText("");
    }//GEN-LAST:event_Background1MouseExited

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void Background1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Background1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Background1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background1;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel OrderLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    // End of variables declaration//GEN-END:variables
}
